
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subscription_app
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - subscription_network

  nginx:
    image: nginx:alpine
    container_name: subscription_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - subscription_network

  db:
    image: mysql:8.0
    container_name: subscription_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: subscription_api
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - subscription_network

networks:
  subscription_network:

volumes:
  db_data:
